/********************************************************************************
** Form generated from reading UI file 'real_ui.ui'
**
** Created by: Qt User Interface Compiler version 5.9.5
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef REAL_UI_H
#define REAL_UI_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLCDNumber>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_RQTGUIControlPluginWidget
{
public:
    QWidget *centralWidget;
    QTabWidget *MANUAL;
    QWidget *manual;
    QSpinBox *joint_2;
    QSpinBox *joint_5;
    QComboBox *RobotMoveMethod;
    QSpinBox *joint_4;
    QSpinBox *goal_y;
    QSpinBox *goal_rz;
    QSpinBox *joint_3;
    QPushButton *SendRobotToGoal;
    QSpinBox *goal_ry;
    QSpinBox *goal_z;
    QSpinBox *goal_x;
    QSpinBox *goal_rx;
    QSpinBox *joint_6;
    QFrame *frame_2;
    QLabel *label_20;
    QLabel *label_51;
    QLabel *label_52;
    QLabel *label_53;
    QLabel *label_54;
    QLabel *label_55;
    QLabel *label_2;
    QCheckBox *load_joint_data;
    QSpinBox *joint_1;
    QPushButton *SendRobotToJointGoal;
    QFrame *frame;
    QLabel *label_56;
    QLabel *label_57;
    QLabel *label_58;
    QLabel *label_59;
    QLabel *label_60;
    QLabel *label_61;
    QFrame *frame_3;
    QLabel *label_62;
    QLabel *label_63;
    QLabel *label_64;
    QLabel *label_65;
    QLabel *label_66;
    QLabel *label_67;
    QLabel *label_3;
    QCheckBox *load_tool_data;
    QPushButton *stop;
    QPushButton *pause;
    QFrame *frame_4;
    QLabel *label_26;
    QPushButton *y_plus;
    QPushButton *z_plus;
    QPushButton *x_plus;
    QPushButton *x_minus;
    QPushButton *z_minus;
    QPushButton *y_minus;
    QFrame *frame_5;
    QLabel *label;
    QComboBox *RobotJogMethod;
    QPushButton *home;
    QPushButton *to_scan_pose;
    QSpinBox *jog_value;
    QPushButton *continue_2;
    QWidget *auto_2;
    QFrame *frame_6;
    QPushButton *start_pick_place;
    QPushButton *stop_2;
    QPushButton *pause_2;
    QPushButton *restart;
    QPushButton *start_3d_detection;
    QLabel *label_27;
    QTabWidget *IO;
    QWidget *tab;
    QLabel *label_25;
    QFrame *frame_14;
    QLCDNumber *j6;
    QLCDNumber *j5;
    QLCDNumber *j4;
    QLCDNumber *j3;
    QLCDNumber *j1;
    QLCDNumber *j2;
    QLabel *label_88;
    QLabel *label_89;
    QLabel *label_90;
    QLabel *label_91;
    QLabel *label_92;
    QLabel *label_93;
    QFrame *frame_13;
    QLCDNumber *tcp_x_12;
    QLCDNumber *tcp_x_11;
    QLCDNumber *tcp_x_10;
    QLCDNumber *tcp_x_9;
    QLCDNumber *tcp_x_7;
    QLCDNumber *tcp_x_8;
    QLabel *label_29;
    QLabel *label_36;
    QLabel *label_83;
    QLabel *label_84;
    QLabel *label_85;
    QLabel *label_86;
    QWidget *tab_2;
    QLCDNumber *io_1;
    QLCDNumber *io_3;
    QLCDNumber *io_2;
    QLCDNumber *io_4;
    QLCDNumber *io_6;
    QLCDNumber *io_5;
    QLCDNumber *io_7;
    QLCDNumber *io_10;
    QLCDNumber *io_11;
    QLCDNumber *io_14;
    QLCDNumber *io_9;
    QLCDNumber *io_8;
    QLCDNumber *io_12;
    QLCDNumber *io_13;
    QLCDNumber *io_17;
    QLCDNumber *io_18;
    QLCDNumber *io_21;
    QLCDNumber *io_16;
    QLCDNumber *io_15;
    QLCDNumber *io_19;
    QLCDNumber *io_20;
    QLCDNumber *rdo_3;
    QLCDNumber *rdo_4;
    QLCDNumber *rdo_7;
    QLCDNumber *rdo_2;
    QLCDNumber *rdo_1;
    QLCDNumber *rdo_5;
    QLCDNumber *rdo_6;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_21;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_28;
    QLabel *label_30;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_37;
    QComboBox *comboBox;
    QPushButton *io_on;
    QPushButton *io_off;
    QPushButton *reset_all_io;
    QFrame *frame_7;

    void setupUi(QWidget *RQTGUIControlPluginWidget)
    {
        if (RQTGUIControlPluginWidget->objectName().isEmpty())
            RQTGUIControlPluginWidget->setObjectName(QStringLiteral("RQTGUIControlPluginWidget"));
        RQTGUIControlPluginWidget->resize(570, 919);
        RQTGUIControlPluginWidget->setAutoFillBackground(false);
        centralWidget = new QWidget(RQTGUIControlPluginWidget);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        MANUAL = new QTabWidget(centralWidget);
        MANUAL->setObjectName(QStringLiteral("MANUAL"));
        MANUAL->setGeometry(QRect(0, 0, 571, 561));
        MANUAL->setStyleSheet(QStringLiteral(""));
        manual = new QWidget();
        manual->setObjectName(QStringLiteral("manual"));
        joint_2 = new QSpinBox(manual);
        joint_2->setObjectName(QStringLiteral("joint_2"));
        joint_2->setGeometry(QRect(380, 100, 48, 26));
        joint_2->setMinimum(-180);
        joint_2->setMaximum(180);
        joint_5 = new QSpinBox(manual);
        joint_5->setObjectName(QStringLiteral("joint_5"));
        joint_5->setGeometry(QRect(380, 170, 48, 26));
        joint_5->setMinimum(-180);
        joint_5->setMaximum(180);
        RobotMoveMethod = new QComboBox(manual);
        RobotMoveMethod->setObjectName(QStringLiteral("RobotMoveMethod"));
        RobotMoveMethod->setGeometry(QRect(10, 190, 135, 25));
        joint_4 = new QSpinBox(manual);
        joint_4->setObjectName(QStringLiteral("joint_4"));
        joint_4->setGeometry(QRect(300, 170, 48, 26));
        joint_4->setMinimum(-180);
        joint_4->setMaximum(180);
        goal_y = new QSpinBox(manual);
        goal_y->setObjectName(QStringLiteral("goal_y"));
        goal_y->setGeometry(QRect(120, 90, 48, 26));
        goal_y->setMinimum(-1000);
        goal_y->setMaximum(1000);
        goal_rz = new QSpinBox(manual);
        goal_rz->setObjectName(QStringLiteral("goal_rz"));
        goal_rz->setGeometry(QRect(200, 150, 48, 26));
        goal_rz->setMinimum(-180);
        goal_rz->setMaximum(180);
        joint_3 = new QSpinBox(manual);
        joint_3->setObjectName(QStringLiteral("joint_3"));
        joint_3->setGeometry(QRect(460, 100, 48, 26));
        joint_3->setMinimum(-180);
        joint_3->setMaximum(180);
        SendRobotToGoal = new QPushButton(manual);
        SendRobotToGoal->setObjectName(QStringLiteral("SendRobotToGoal"));
        SendRobotToGoal->setGeometry(QRect(10, 220, 251, 41));
        SendRobotToGoal->setStyleSheet(QStringLiteral("background-color: rgb(150,220, 150)"));
        goal_ry = new QSpinBox(manual);
        goal_ry->setObjectName(QStringLiteral("goal_ry"));
        goal_ry->setGeometry(QRect(120, 150, 48, 26));
        goal_ry->setMinimum(-180);
        goal_ry->setMaximum(180);
        goal_z = new QSpinBox(manual);
        goal_z->setObjectName(QStringLiteral("goal_z"));
        goal_z->setGeometry(QRect(200, 90, 48, 26));
        goal_z->setMinimum(-1000);
        goal_z->setMaximum(1000);
        goal_x = new QSpinBox(manual);
        goal_x->setObjectName(QStringLiteral("goal_x"));
        goal_x->setGeometry(QRect(40, 90, 48, 26));
        goal_x->setMinimum(-1000);
        goal_x->setMaximum(1000);
        goal_rx = new QSpinBox(manual);
        goal_rx->setObjectName(QStringLiteral("goal_rx"));
        goal_rx->setGeometry(QRect(40, 150, 48, 26));
        goal_rx->setMinimum(-180);
        goal_rx->setMaximum(180);
        joint_6 = new QSpinBox(manual);
        joint_6->setObjectName(QStringLiteral("joint_6"));
        joint_6->setGeometry(QRect(460, 170, 48, 26));
        joint_6->setMinimum(-180);
        joint_6->setMaximum(180);
        frame_2 = new QFrame(manual);
        frame_2->setObjectName(QStringLiteral("frame_2"));
        frame_2->setGeometry(QRect(280, 50, 251, 211));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Raised);
        label_20 = new QLabel(frame_2);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(120, 30, 67, 17));
        label_51 = new QLabel(frame_2);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(200, 30, 67, 17));
        label_52 = new QLabel(frame_2);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(40, 30, 67, 17));
        label_53 = new QLabel(frame_2);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(40, 100, 67, 17));
        label_54 = new QLabel(frame_2);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(200, 100, 67, 17));
        label_55 = new QLabel(frame_2);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(120, 100, 67, 17));
        label_2 = new QLabel(frame_2);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(80, 0, 101, 17));
        load_joint_data = new QCheckBox(frame_2);
        load_joint_data->setObjectName(QStringLiteral("load_joint_data"));
        load_joint_data->setGeometry(QRect(150, 150, 92, 23));
        label_2->raise();
        label_20->raise();
        label_51->raise();
        label_52->raise();
        label_53->raise();
        label_54->raise();
        label_55->raise();
        load_joint_data->raise();
        joint_1 = new QSpinBox(manual);
        joint_1->setObjectName(QStringLiteral("joint_1"));
        joint_1->setGeometry(QRect(300, 100, 48, 26));
        joint_1->setMinimum(-180);
        joint_1->setMaximum(180);
        SendRobotToJointGoal = new QPushButton(manual);
        SendRobotToJointGoal->setObjectName(QStringLiteral("SendRobotToJointGoal"));
        SendRobotToJointGoal->setGeometry(QRect(280, 220, 251, 41));
        SendRobotToJointGoal->setStyleSheet(QStringLiteral("background-color: rgb(150,220, 150)"));
        frame = new QFrame(manual);
        frame->setObjectName(QStringLiteral("frame"));
        frame->setGeometry(QRect(10, 50, 251, 211));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        label_56 = new QLabel(frame);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(40, 20, 67, 17));
        label_57 = new QLabel(frame);
        label_57->setObjectName(QStringLiteral("label_57"));
        label_57->setGeometry(QRect(120, 20, 67, 17));
        label_58 = new QLabel(frame);
        label_58->setObjectName(QStringLiteral("label_58"));
        label_58->setGeometry(QRect(210, 20, 67, 17));
        label_59 = new QLabel(frame);
        label_59->setObjectName(QStringLiteral("label_59"));
        label_59->setGeometry(QRect(40, 80, 67, 17));
        label_60 = new QLabel(frame);
        label_60->setObjectName(QStringLiteral("label_60"));
        label_60->setGeometry(QRect(200, 80, 67, 17));
        label_61 = new QLabel(frame);
        label_61->setObjectName(QStringLiteral("label_61"));
        label_61->setGeometry(QRect(120, 80, 67, 17));
        frame_3 = new QFrame(frame);
        frame_3->setObjectName(QStringLiteral("frame_3"));
        frame_3->setGeometry(QRect(40, 210, 251, 211));
        frame_3->setFrameShape(QFrame::StyledPanel);
        frame_3->setFrameShadow(QFrame::Raised);
        label_62 = new QLabel(frame_3);
        label_62->setObjectName(QStringLiteral("label_62"));
        label_62->setGeometry(QRect(20, 10, 67, 17));
        label_63 = new QLabel(frame_3);
        label_63->setObjectName(QStringLiteral("label_63"));
        label_63->setGeometry(QRect(100, 10, 67, 17));
        label_64 = new QLabel(frame_3);
        label_64->setObjectName(QStringLiteral("label_64"));
        label_64->setGeometry(QRect(190, 10, 67, 17));
        label_65 = new QLabel(frame_3);
        label_65->setObjectName(QStringLiteral("label_65"));
        label_65->setGeometry(QRect(20, 70, 67, 17));
        label_66 = new QLabel(frame_3);
        label_66->setObjectName(QStringLiteral("label_66"));
        label_66->setGeometry(QRect(180, 70, 67, 17));
        label_67 = new QLabel(frame_3);
        label_67->setObjectName(QStringLiteral("label_67"));
        label_67->setGeometry(QRect(100, 70, 67, 17));
        label_3 = new QLabel(frame);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(90, 0, 81, 17));
        load_tool_data = new QCheckBox(frame);
        load_tool_data->setObjectName(QStringLiteral("load_tool_data"));
        load_tool_data->setGeometry(QRect(160, 150, 92, 23));
        stop = new QPushButton(manual);
        stop->setObjectName(QStringLiteral("stop"));
        stop->setGeometry(QRect(430, 270, 101, 51));
        pause = new QPushButton(manual);
        pause->setObjectName(QStringLiteral("pause"));
        pause->setGeometry(QRect(430, 360, 101, 51));
        frame_4 = new QFrame(manual);
        frame_4->setObjectName(QStringLiteral("frame_4"));
        frame_4->setGeometry(QRect(0, 0, 581, 531));
        frame_4->setStyleSheet(QStringLiteral("background-color: rgba(50, 115, 220, 0.3);"));
        frame_4->setFrameShape(QFrame::StyledPanel);
        frame_4->setFrameShadow(QFrame::Raised);
        label_26 = new QLabel(frame_4);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(10, 0, 571, 31));
        label_26->setStyleSheet(QLatin1String("background-color: rgba(50, 115, 220, 0.3);\n"
"font: 57 14pt \"Ubuntu\";"));
        y_plus = new QPushButton(frame_4);
        y_plus->setObjectName(QStringLiteral("y_plus"));
        y_plus->setGeometry(QRect(90, 340, 89, 51));
        y_plus->setStyleSheet(QStringLiteral("background-color: rgba(115, 50, 220, 0.3);"));
        z_plus = new QPushButton(frame_4);
        z_plus->setObjectName(QStringLiteral("z_plus"));
        z_plus->setGeometry(QRect(188, 360, 61, 51));
        z_plus->setStyleSheet(QStringLiteral("background-color: rgba(115, 220, 50, 0.3);"));
        x_plus = new QPushButton(frame_4);
        x_plus->setObjectName(QStringLiteral("x_plus"));
        x_plus->setGeometry(QRect(20, 360, 61, 51));
        x_plus->setStyleSheet(QStringLiteral("background-color: rgba(220, 115, 50, 0.3);"));
        x_minus = new QPushButton(frame_4);
        x_minus->setObjectName(QStringLiteral("x_minus"));
        x_minus->setGeometry(QRect(20, 420, 61, 51));
        x_minus->setStyleSheet(QStringLiteral("background-color: rgba(220, 115, 50, 0.3);"));
        z_minus = new QPushButton(frame_4);
        z_minus->setObjectName(QStringLiteral("z_minus"));
        z_minus->setGeometry(QRect(188, 420, 61, 51));
        z_minus->setStyleSheet(QStringLiteral("background-color: rgba(115, 220, 50, 0.3);"));
        y_minus = new QPushButton(frame_4);
        y_minus->setObjectName(QStringLiteral("y_minus"));
        y_minus->setGeometry(QRect(90, 440, 89, 51));
        y_minus->setStyleSheet(QStringLiteral("background-color: rgba(115, 50, 220, 0.3);"));
        frame_5 = new QFrame(frame_4);
        frame_5->setObjectName(QStringLiteral("frame_5"));
        frame_5->setGeometry(QRect(10, 280, 251, 221));
        frame_5->setFrameShape(QFrame::StyledPanel);
        frame_5->setFrameShadow(QFrame::Raised);
        label = new QLabel(frame_5);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(80, 0, 101, 17));
        RobotJogMethod = new QComboBox(frame_5);
        RobotJogMethod->setObjectName(QStringLiteral("RobotJogMethod"));
        RobotJogMethod->setGeometry(QRect(0, 20, 135, 25));
        home = new QPushButton(frame_4);
        home->setObjectName(QStringLiteral("home"));
        home->setGeometry(QRect(300, 270, 111, 51));
        to_scan_pose = new QPushButton(frame_4);
        to_scan_pose->setObjectName(QStringLiteral("to_scan_pose"));
        to_scan_pose->setGeometry(QRect(300, 360, 111, 51));
        frame_5->raise();
        label_26->raise();
        y_plus->raise();
        z_plus->raise();
        x_plus->raise();
        x_minus->raise();
        z_minus->raise();
        y_minus->raise();
        home->raise();
        to_scan_pose->raise();
        jog_value = new QSpinBox(manual);
        jog_value->setObjectName(QStringLiteral("jog_value"));
        jog_value->setGeometry(QRect(110, 400, 51, 26));
        jog_value->setMinimum(-200);
        jog_value->setMaximum(200);
        continue_2 = new QPushButton(manual);
        continue_2->setObjectName(QStringLiteral("continue_2"));
        continue_2->setGeometry(QRect(430, 420, 101, 51));
        MANUAL->addTab(manual, QString());
        frame_4->raise();
        frame->raise();
        frame_2->raise();
        joint_2->raise();
        joint_5->raise();
        RobotMoveMethod->raise();
        joint_4->raise();
        goal_y->raise();
        goal_rz->raise();
        joint_3->raise();
        SendRobotToGoal->raise();
        goal_ry->raise();
        goal_z->raise();
        goal_x->raise();
        goal_rx->raise();
        joint_6->raise();
        joint_1->raise();
        SendRobotToJointGoal->raise();
        stop->raise();
        pause->raise();
        jog_value->raise();
        continue_2->raise();
        auto_2 = new QWidget();
        auto_2->setObjectName(QStringLiteral("auto_2"));
        frame_6 = new QFrame(auto_2);
        frame_6->setObjectName(QStringLiteral("frame_6"));
        frame_6->setGeometry(QRect(-20, -60, 681, 591));
        frame_6->setStyleSheet(QStringLiteral("background-color: rgba(220, 50, 115, 0.3);"));
        frame_6->setFrameShape(QFrame::StyledPanel);
        frame_6->setFrameShadow(QFrame::Raised);
        start_pick_place = new QPushButton(frame_6);
        start_pick_place->setObjectName(QStringLiteral("start_pick_place"));
        start_pick_place->setGeometry(QRect(10, 220, 581, 71));
        stop_2 = new QPushButton(frame_6);
        stop_2->setObjectName(QStringLiteral("stop_2"));
        stop_2->setGeometry(QRect(10, 310, 581, 61));
        pause_2 = new QPushButton(frame_6);
        pause_2->setObjectName(QStringLiteral("pause_2"));
        pause_2->setGeometry(QRect(10, 390, 581, 61));
        restart = new QPushButton(frame_6);
        restart->setObjectName(QStringLiteral("restart"));
        restart->setGeometry(QRect(10, 470, 581, 61));
        start_3d_detection = new QPushButton(frame_6);
        start_3d_detection->setObjectName(QStringLiteral("start_3d_detection"));
        start_3d_detection->setGeometry(QRect(8, 130, 581, 61));
        label_27 = new QLabel(frame_6);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(20, 60, 571, 31));
        label_27->setStyleSheet(QLatin1String("background-color: rgba(220, 50, 115, 0.3);\n"
"font: 57 14pt \"Ubuntu\";"));
        MANUAL->addTab(auto_2, QString());
        IO = new QTabWidget(centralWidget);
        IO->setObjectName(QStringLiteral("IO"));
        IO->setGeometry(QRect(0, 530, 581, 391));
        IO->setStyleSheet(QStringLiteral("background-color: rgba(50, 115, 220, 0.01);"));
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        label_25 = new QLabel(tab);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(-10, -40, 571, 31));
        label_25->setStyleSheet(QLatin1String("background-color: rgba(220, 50, 115, 0.3);\n"
"font: 57 18pt \"Ubuntu\";"));
        frame_14 = new QFrame(tab);
        frame_14->setObjectName(QStringLiteral("frame_14"));
        frame_14->setGeometry(QRect(0, 160, 611, 211));
        frame_14->setStyleSheet(QStringLiteral("background-color: rgba(220, 50, 115, 0.3);"));
        frame_14->setFrameShape(QFrame::StyledPanel);
        frame_14->setFrameShadow(QFrame::Raised);
        j6 = new QLCDNumber(frame_14);
        j6->setObjectName(QStringLiteral("j6"));
        j6->setGeometry(QRect(350, 90, 121, 31));
        j6->setStyleSheet(QStringLiteral("background-color: rgb(150,200, 150)"));
        j6->setSmallDecimalPoint(true);
        j5 = new QLCDNumber(frame_14);
        j5->setObjectName(QStringLiteral("j5"));
        j5->setGeometry(QRect(350, 50, 121, 31));
        j5->setStyleSheet(QStringLiteral("background-color: rgb(150,200, 150)"));
        j5->setSmallDecimalPoint(true);
        j4 = new QLCDNumber(frame_14);
        j4->setObjectName(QStringLiteral("j4"));
        j4->setGeometry(QRect(350, 10, 121, 31));
        j4->setStyleSheet(QStringLiteral("background-color: rgb(150,200, 150)"));
        j4->setFrameShape(QFrame::StyledPanel);
        j4->setSmallDecimalPoint(true);
        j3 = new QLCDNumber(frame_14);
        j3->setObjectName(QStringLiteral("j3"));
        j3->setGeometry(QRect(80, 90, 101, 31));
        j3->setStyleSheet(QStringLiteral("background-color: rgb(150,200, 150)"));
        j3->setSmallDecimalPoint(true);
        j1 = new QLCDNumber(frame_14);
        j1->setObjectName(QStringLiteral("j1"));
        j1->setGeometry(QRect(80, 12, 101, 31));
        j1->setStyleSheet(QStringLiteral("background-color: rgb(150,200, 150)"));
        j1->setSmallDecimalPoint(true);
        j2 = new QLCDNumber(frame_14);
        j2->setObjectName(QStringLiteral("j2"));
        j2->setGeometry(QRect(80, 50, 101, 31));
        j2->setStyleSheet(QStringLiteral("background-color: rgb(150,200, 150)"));
        j2->setSmallDecimalPoint(true);
        label_88 = new QLabel(frame_14);
        label_88->setObjectName(QStringLiteral("label_88"));
        label_88->setGeometry(QRect(310, 60, 31, 21));
        label_89 = new QLabel(frame_14);
        label_89->setObjectName(QStringLiteral("label_89"));
        label_89->setGeometry(QRect(310, 100, 31, 21));
        label_90 = new QLabel(frame_14);
        label_90->setObjectName(QStringLiteral("label_90"));
        label_90->setGeometry(QRect(310, 20, 31, 21));
        label_91 = new QLabel(frame_14);
        label_91->setObjectName(QStringLiteral("label_91"));
        label_91->setGeometry(QRect(50, 20, 31, 21));
        label_92 = new QLabel(frame_14);
        label_92->setObjectName(QStringLiteral("label_92"));
        label_92->setGeometry(QRect(50, 60, 31, 21));
        label_93 = new QLabel(frame_14);
        label_93->setObjectName(QStringLiteral("label_93"));
        label_93->setGeometry(QRect(50, 100, 31, 21));
        frame_13 = new QFrame(tab);
        frame_13->setObjectName(QStringLiteral("frame_13"));
        frame_13->setGeometry(QRect(-10, -10, 581, 171));
        frame_13->setStyleSheet(QStringLiteral("background-color: rgba(220, 50, 115, 0.3);"));
        frame_13->setFrameShape(QFrame::StyledPanel);
        frame_13->setFrameShadow(QFrame::Raised);
        tcp_x_12 = new QLCDNumber(frame_13);
        tcp_x_12->setObjectName(QStringLiteral("tcp_x_12"));
        tcp_x_12->setGeometry(QRect(365, 110, 121, 31));
        tcp_x_12->setStyleSheet(QStringLiteral("background-color: rgb(150,200, 150)"));
        tcp_x_12->setSmallDecimalPoint(true);
        tcp_x_11 = new QLCDNumber(frame_13);
        tcp_x_11->setObjectName(QStringLiteral("tcp_x_11"));
        tcp_x_11->setGeometry(QRect(365, 70, 121, 31));
        tcp_x_11->setStyleSheet(QStringLiteral("background-color: rgb(150,200, 150)"));
        tcp_x_11->setSmallDecimalPoint(true);
        tcp_x_10 = new QLCDNumber(frame_13);
        tcp_x_10->setObjectName(QStringLiteral("tcp_x_10"));
        tcp_x_10->setGeometry(QRect(365, 30, 121, 31));
        tcp_x_10->setStyleSheet(QStringLiteral("background-color: rgb(150,200, 150)"));
        tcp_x_10->setFrameShape(QFrame::StyledPanel);
        tcp_x_10->setSmallDecimalPoint(true);
        tcp_x_9 = new QLCDNumber(frame_13);
        tcp_x_9->setObjectName(QStringLiteral("tcp_x_9"));
        tcp_x_9->setGeometry(QRect(95, 110, 101, 31));
        tcp_x_9->setStyleSheet(QStringLiteral("background-color: rgb(150,200, 150)"));
        tcp_x_9->setSmallDecimalPoint(true);
        tcp_x_7 = new QLCDNumber(frame_13);
        tcp_x_7->setObjectName(QStringLiteral("tcp_x_7"));
        tcp_x_7->setGeometry(QRect(95, 32, 101, 31));
        tcp_x_7->setStyleSheet(QStringLiteral("background-color: rgb(150,200, 150)"));
        tcp_x_7->setSmallDecimalPoint(true);
        tcp_x_8 = new QLCDNumber(frame_13);
        tcp_x_8->setObjectName(QStringLiteral("tcp_x_8"));
        tcp_x_8->setGeometry(QRect(95, 70, 101, 31));
        tcp_x_8->setStyleSheet(QStringLiteral("background-color: rgb(150,200, 150)"));
        tcp_x_8->setSmallDecimalPoint(true);
        label_29 = new QLabel(frame_13);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(70, 40, 21, 21));
        label_36 = new QLabel(frame_13);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(70, 80, 21, 21));
        label_83 = new QLabel(frame_13);
        label_83->setObjectName(QStringLiteral("label_83"));
        label_83->setGeometry(QRect(70, 120, 21, 21));
        label_84 = new QLabel(frame_13);
        label_84->setObjectName(QStringLiteral("label_84"));
        label_84->setGeometry(QRect(325, 80, 31, 21));
        label_85 = new QLabel(frame_13);
        label_85->setObjectName(QStringLiteral("label_85"));
        label_85->setGeometry(QRect(325, 120, 31, 21));
        label_86 = new QLabel(frame_13);
        label_86->setObjectName(QStringLiteral("label_86"));
        label_86->setGeometry(QRect(325, 40, 31, 21));
        IO->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        io_1 = new QLCDNumber(tab_2);
        io_1->setObjectName(QStringLiteral("io_1"));
        io_1->setGeometry(QRect(70, 82, 64, 23));
        io_1->setStyleSheet(QStringLiteral("background-color: rgb(77,120, 255)"));
        io_1->setSmallDecimalPoint(true);
        io_3 = new QLCDNumber(tab_2);
        io_3->setObjectName(QStringLiteral("io_3"));
        io_3->setGeometry(QRect(70, 140, 64, 23));
        io_3->setStyleSheet(QStringLiteral("background-color: rgb(77,120, 255)"));
        io_2 = new QLCDNumber(tab_2);
        io_2->setObjectName(QStringLiteral("io_2"));
        io_2->setGeometry(QRect(70, 111, 64, 23));
        io_2->setAutoFillBackground(true);
        io_2->setStyleSheet(QStringLiteral("background-color: rgb(77,120, 255)"));
        io_4 = new QLCDNumber(tab_2);
        io_4->setObjectName(QStringLiteral("io_4"));
        io_4->setGeometry(QRect(70, 169, 64, 23));
        io_4->setStyleSheet(QStringLiteral("background-color: rgb(77,120, 255)"));
        io_6 = new QLCDNumber(tab_2);
        io_6->setObjectName(QStringLiteral("io_6"));
        io_6->setGeometry(QRect(70, 228, 64, 23));
        io_6->setStyleSheet(QStringLiteral("background-color: rgb(77,120, 255)"));
        io_5 = new QLCDNumber(tab_2);
        io_5->setObjectName(QStringLiteral("io_5"));
        io_5->setGeometry(QRect(70, 199, 64, 23));
        io_5->setStyleSheet(QStringLiteral("background-color: rgb(77,120, 255)"));
        io_7 = new QLCDNumber(tab_2);
        io_7->setObjectName(QStringLiteral("io_7"));
        io_7->setGeometry(QRect(70, 257, 64, 23));
        io_7->setStyleSheet(QStringLiteral("background-color: rgb(77,120, 255)"));
        io_10 = new QLCDNumber(tab_2);
        io_10->setObjectName(QStringLiteral("io_10"));
        io_10->setGeometry(QRect(210, 142, 64, 23));
        io_10->setStyleSheet(QStringLiteral("background-color: rgb(77,120, 255)"));
        io_11 = new QLCDNumber(tab_2);
        io_11->setObjectName(QStringLiteral("io_11"));
        io_11->setGeometry(QRect(210, 171, 64, 23));
        io_11->setStyleSheet(QStringLiteral("background-color: rgb(77,120, 255)"));
        io_14 = new QLCDNumber(tab_2);
        io_14->setObjectName(QStringLiteral("io_14"));
        io_14->setGeometry(QRect(210, 259, 64, 23));
        io_14->setStyleSheet(QStringLiteral("background-color: rgb(77,120, 255)"));
        io_9 = new QLCDNumber(tab_2);
        io_9->setObjectName(QStringLiteral("io_9"));
        io_9->setGeometry(QRect(210, 113, 64, 23));
        io_9->setStyleSheet(QStringLiteral("background-color: rgb(77,120, 255)"));
        io_8 = new QLCDNumber(tab_2);
        io_8->setObjectName(QStringLiteral("io_8"));
        io_8->setGeometry(QRect(210, 84, 64, 23));
        io_8->setStyleSheet(QStringLiteral("background-color: rgb(77,120, 255)"));
        io_12 = new QLCDNumber(tab_2);
        io_12->setObjectName(QStringLiteral("io_12"));
        io_12->setGeometry(QRect(210, 201, 64, 23));
        io_12->setStyleSheet(QStringLiteral("background-color: rgb(77,120, 255)"));
        io_13 = new QLCDNumber(tab_2);
        io_13->setObjectName(QStringLiteral("io_13"));
        io_13->setGeometry(QRect(210, 230, 64, 23));
        io_13->setStyleSheet(QStringLiteral("background-color: rgb(77,120, 255)"));
        io_17 = new QLCDNumber(tab_2);
        io_17->setObjectName(QStringLiteral("io_17"));
        io_17->setGeometry(QRect(340, 141, 64, 23));
        io_17->setStyleSheet(QStringLiteral("background-color: rgb(77,120, 255)"));
        io_18 = new QLCDNumber(tab_2);
        io_18->setObjectName(QStringLiteral("io_18"));
        io_18->setGeometry(QRect(340, 170, 64, 23));
        io_18->setStyleSheet(QStringLiteral("background-color: rgb(77,120, 255)"));
        io_21 = new QLCDNumber(tab_2);
        io_21->setObjectName(QStringLiteral("io_21"));
        io_21->setGeometry(QRect(340, 258, 64, 23));
        io_21->setStyleSheet(QStringLiteral("background-color: rgb(77,120, 255)"));
        io_16 = new QLCDNumber(tab_2);
        io_16->setObjectName(QStringLiteral("io_16"));
        io_16->setGeometry(QRect(340, 112, 64, 23));
        io_16->setStyleSheet(QStringLiteral("background-color: rgb(77,120, 255)"));
        io_15 = new QLCDNumber(tab_2);
        io_15->setObjectName(QStringLiteral("io_15"));
        io_15->setGeometry(QRect(340, 83, 64, 23));
        io_15->setStyleSheet(QStringLiteral("background-color: rgb(77,120, 255)"));
        io_19 = new QLCDNumber(tab_2);
        io_19->setObjectName(QStringLiteral("io_19"));
        io_19->setGeometry(QRect(340, 200, 64, 23));
        io_19->setStyleSheet(QStringLiteral("background-color: rgb(77,120, 255)"));
        io_20 = new QLCDNumber(tab_2);
        io_20->setObjectName(QStringLiteral("io_20"));
        io_20->setGeometry(QRect(340, 229, 64, 23));
        io_20->setStyleSheet(QStringLiteral("background-color: rgb(77,120, 255)"));
        rdo_3 = new QLCDNumber(tab_2);
        rdo_3->setObjectName(QStringLiteral("rdo_3"));
        rdo_3->setGeometry(QRect(480, 141, 64, 23));
        rdo_3->setStyleSheet(QStringLiteral("background-color: rgb(77,120, 255)"));
        rdo_4 = new QLCDNumber(tab_2);
        rdo_4->setObjectName(QStringLiteral("rdo_4"));
        rdo_4->setGeometry(QRect(480, 170, 64, 23));
        rdo_4->setStyleSheet(QStringLiteral("background-color: rgb(77,120, 255)"));
        rdo_7 = new QLCDNumber(tab_2);
        rdo_7->setObjectName(QStringLiteral("rdo_7"));
        rdo_7->setGeometry(QRect(480, 258, 64, 23));
        rdo_7->setStyleSheet(QStringLiteral("background-color: rgb(77,120, 255)"));
        rdo_2 = new QLCDNumber(tab_2);
        rdo_2->setObjectName(QStringLiteral("rdo_2"));
        rdo_2->setGeometry(QRect(480, 112, 64, 23));
        rdo_2->setStyleSheet(QStringLiteral("background-color: rgb(77,120, 255)"));
        rdo_1 = new QLCDNumber(tab_2);
        rdo_1->setObjectName(QStringLiteral("rdo_1"));
        rdo_1->setGeometry(QRect(480, 83, 64, 23));
        rdo_1->setStyleSheet(QStringLiteral("background-color: rgb(77,120, 255)"));
        rdo_5 = new QLCDNumber(tab_2);
        rdo_5->setObjectName(QStringLiteral("rdo_5"));
        rdo_5->setGeometry(QRect(480, 200, 64, 23));
        rdo_5->setStyleSheet(QStringLiteral("background-color: rgb(77,120, 255)"));
        rdo_6 = new QLCDNumber(tab_2);
        rdo_6->setObjectName(QStringLiteral("rdo_6"));
        rdo_6->setGeometry(QRect(480, 229, 64, 23));
        rdo_6->setStyleSheet(QStringLiteral("background-color: rgb(77,120, 255)"));
        label_4 = new QLabel(tab_2);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(20, 79, 51, 31));
        label_5 = new QLabel(tab_2);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(20, 109, 51, 31));
        label_6 = new QLabel(tab_2);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(20, 139, 51, 31));
        label_7 = new QLabel(tab_2);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(20, 169, 51, 31));
        label_8 = new QLabel(tab_2);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(20, 199, 51, 31));
        label_9 = new QLabel(tab_2);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(20, 229, 51, 31));
        label_10 = new QLabel(tab_2);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(20, 259, 51, 31));
        label_11 = new QLabel(tab_2);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(160, 79, 51, 31));
        label_12 = new QLabel(tab_2);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(160, 229, 51, 31));
        label_13 = new QLabel(tab_2);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(160, 169, 51, 31));
        label_14 = new QLabel(tab_2);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(160, 109, 51, 31));
        label_15 = new QLabel(tab_2);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(160, 199, 51, 31));
        label_16 = new QLabel(tab_2);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(160, 139, 51, 31));
        label_17 = new QLabel(tab_2);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(160, 259, 51, 31));
        label_18 = new QLabel(tab_2);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(290, 79, 51, 31));
        label_19 = new QLabel(tab_2);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(290, 229, 51, 31));
        label_21 = new QLabel(tab_2);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(290, 169, 51, 31));
        label_22 = new QLabel(tab_2);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(290, 109, 51, 31));
        label_23 = new QLabel(tab_2);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(290, 199, 51, 31));
        label_24 = new QLabel(tab_2);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(290, 139, 51, 31));
        label_28 = new QLabel(tab_2);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(290, 259, 51, 31));
        label_30 = new QLabel(tab_2);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(420, 79, 51, 31));
        label_31 = new QLabel(tab_2);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(420, 229, 51, 31));
        label_32 = new QLabel(tab_2);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(420, 169, 51, 31));
        label_33 = new QLabel(tab_2);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(420, 109, 51, 31));
        label_34 = new QLabel(tab_2);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(420, 199, 51, 31));
        label_35 = new QLabel(tab_2);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(420, 139, 51, 31));
        label_37 = new QLabel(tab_2);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(420, 259, 51, 31));
        comboBox = new QComboBox(tab_2);
        comboBox->setObjectName(QStringLiteral("comboBox"));
        comboBox->setGeometry(QRect(210, 20, 101, 31));
        comboBox->setStyleSheet(QStringLiteral("background-color: rgba(50, 150, 150, 0.3);"));
        io_on = new QPushButton(tab_2);
        io_on->setObjectName(QStringLiteral("io_on"));
        io_on->setGeometry(QRect(320, 10, 41, 41));
        io_on->setStyleSheet(QStringLiteral("background-color: rgba(50, 250, 50, 0.3);"));
        io_off = new QPushButton(tab_2);
        io_off->setObjectName(QStringLiteral("io_off"));
        io_off->setGeometry(QRect(370, 10, 41, 41));
        io_off->setStyleSheet(QStringLiteral("background-color: rgba(250, 50, 50, 0.3);"));
        reset_all_io = new QPushButton(tab_2);
        reset_all_io->setObjectName(QStringLiteral("reset_all_io"));
        reset_all_io->setGeometry(QRect(440, 10, 101, 41));
        reset_all_io->setStyleSheet(QStringLiteral("background-color: rgba(250, 10, 10, 0.8);"));
        frame_7 = new QFrame(tab_2);
        frame_7->setObjectName(QStringLiteral("frame_7"));
        frame_7->setGeometry(QRect(0, 60, 571, 301));
        frame_7->setFrameShape(QFrame::StyledPanel);
        frame_7->setFrameShadow(QFrame::Raised);
        IO->addTab(tab_2, QString());
        frame_7->raise();
        io_1->raise();
        io_3->raise();
        io_2->raise();
        io_4->raise();
        io_6->raise();
        io_5->raise();
        io_7->raise();
        io_10->raise();
        io_11->raise();
        io_14->raise();
        io_9->raise();
        io_8->raise();
        io_12->raise();
        io_13->raise();
        io_17->raise();
        io_18->raise();
        io_21->raise();
        io_16->raise();
        io_15->raise();
        io_19->raise();
        io_20->raise();
        rdo_3->raise();
        rdo_4->raise();
        rdo_7->raise();
        rdo_2->raise();
        rdo_1->raise();
        rdo_5->raise();
        rdo_6->raise();
        label_4->raise();
        label_5->raise();
        label_6->raise();
        label_7->raise();
        label_8->raise();
        label_9->raise();
        label_10->raise();
        label_11->raise();
        label_12->raise();
        label_13->raise();
        label_14->raise();
        label_15->raise();
        label_16->raise();
        label_17->raise();
        label_18->raise();
        label_19->raise();
        label_21->raise();
        label_22->raise();
        label_23->raise();
        label_24->raise();
        label_28->raise();
        label_30->raise();
        label_31->raise();
        label_32->raise();
        label_33->raise();
        label_34->raise();
        label_35->raise();
        label_37->raise();
        comboBox->raise();
        io_on->raise();
        io_off->raise();
        reset_all_io->raise();

        retranslateUi(RQTGUIControlPluginWidget);

        MANUAL->setCurrentIndex(0);
        IO->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(RQTGUIControlPluginWidget);
    } // setupUi

    void retranslateUi(QWidget *RQTGUIControlPluginWidget)
    {
        RQTGUIControlPluginWidget->setWindowTitle(QApplication::translate("RQTGUIControlPluginWidget", "RQTGUIControlPluginWidget", Q_NULLPTR));
        RobotMoveMethod->clear();
        RobotMoveMethod->insertItems(0, QStringList()
         << QApplication::translate("RQTGUIControlPluginWidget", "World", Q_NULLPTR)
         << QApplication::translate("RQTGUIControlPluginWidget", "Joint", Q_NULLPTR)
        );
        SendRobotToGoal->setText(QApplication::translate("RQTGUIControlPluginWidget", "SendRobotToGoal", Q_NULLPTR));
        label_20->setText(QApplication::translate("RQTGUIControlPluginWidget", "J2", Q_NULLPTR));
        label_51->setText(QApplication::translate("RQTGUIControlPluginWidget", "J3", Q_NULLPTR));
        label_52->setText(QApplication::translate("RQTGUIControlPluginWidget", "J1", Q_NULLPTR));
        label_53->setText(QApplication::translate("RQTGUIControlPluginWidget", "J4", Q_NULLPTR));
        label_54->setText(QApplication::translate("RQTGUIControlPluginWidget", "J6", Q_NULLPTR));
        label_55->setText(QApplication::translate("RQTGUIControlPluginWidget", "J5", Q_NULLPTR));
        label_2->setText(QApplication::translate("RQTGUIControlPluginWidget", "Joint Control", Q_NULLPTR));
        load_joint_data->setText(QApplication::translate("RQTGUIControlPluginWidget", "load data", Q_NULLPTR));
        SendRobotToJointGoal->setText(QApplication::translate("RQTGUIControlPluginWidget", "SendRobotToJointGoal", Q_NULLPTR));
        label_56->setText(QApplication::translate("RQTGUIControlPluginWidget", "X", Q_NULLPTR));
        label_57->setText(QApplication::translate("RQTGUIControlPluginWidget", "Y", Q_NULLPTR));
        label_58->setText(QApplication::translate("RQTGUIControlPluginWidget", "Z", Q_NULLPTR));
        label_59->setText(QApplication::translate("RQTGUIControlPluginWidget", "RX", Q_NULLPTR));
        label_60->setText(QApplication::translate("RQTGUIControlPluginWidget", "RZ", Q_NULLPTR));
        label_61->setText(QApplication::translate("RQTGUIControlPluginWidget", "RY", Q_NULLPTR));
        label_62->setText(QApplication::translate("RQTGUIControlPluginWidget", "goal_x", Q_NULLPTR));
        label_63->setText(QApplication::translate("RQTGUIControlPluginWidget", "goal_y", Q_NULLPTR));
        label_64->setText(QApplication::translate("RQTGUIControlPluginWidget", "goal_z", Q_NULLPTR));
        label_65->setText(QApplication::translate("RQTGUIControlPluginWidget", "goal_rx", Q_NULLPTR));
        label_66->setText(QApplication::translate("RQTGUIControlPluginWidget", "goal_rz", Q_NULLPTR));
        label_67->setText(QApplication::translate("RQTGUIControlPluginWidget", "goal_ry", Q_NULLPTR));
        label_3->setText(QApplication::translate("RQTGUIControlPluginWidget", "Tool control", Q_NULLPTR));
        load_tool_data->setText(QApplication::translate("RQTGUIControlPluginWidget", "load data", Q_NULLPTR));
        stop->setText(QApplication::translate("RQTGUIControlPluginWidget", "STOP", Q_NULLPTR));
        pause->setText(QApplication::translate("RQTGUIControlPluginWidget", "PAUSE", Q_NULLPTR));
        label_26->setText(QApplication::translate("RQTGUIControlPluginWidget", "                                       Manual Robot Operations", Q_NULLPTR));
        y_plus->setText(QApplication::translate("RQTGUIControlPluginWidget", "Y+", Q_NULLPTR));
        z_plus->setText(QApplication::translate("RQTGUIControlPluginWidget", "Z+", Q_NULLPTR));
        x_plus->setText(QApplication::translate("RQTGUIControlPluginWidget", "X+", Q_NULLPTR));
        x_minus->setText(QApplication::translate("RQTGUIControlPluginWidget", "X-", Q_NULLPTR));
        z_minus->setText(QApplication::translate("RQTGUIControlPluginWidget", "Z-", Q_NULLPTR));
        y_minus->setText(QApplication::translate("RQTGUIControlPluginWidget", "Y-", Q_NULLPTR));
        label->setText(QApplication::translate("RQTGUIControlPluginWidget", "Robot Jogger", Q_NULLPTR));
        RobotJogMethod->clear();
        RobotJogMethod->insertItems(0, QStringList()
         << QApplication::translate("RQTGUIControlPluginWidget", "World", Q_NULLPTR)
         << QApplication::translate("RQTGUIControlPluginWidget", "Tool", Q_NULLPTR)
        );
        home->setText(QApplication::translate("RQTGUIControlPluginWidget", "HOME", Q_NULLPTR));
        to_scan_pose->setText(QApplication::translate("RQTGUIControlPluginWidget", "SCAN POSE", Q_NULLPTR));
        continue_2->setText(QApplication::translate("RQTGUIControlPluginWidget", "CONTINUE", Q_NULLPTR));
        MANUAL->setTabText(MANUAL->indexOf(manual), QApplication::translate("RQTGUIControlPluginWidget", "MANUAL", Q_NULLPTR));
        start_pick_place->setText(QApplication::translate("RQTGUIControlPluginWidget", "START PICK PLACE", Q_NULLPTR));
        stop_2->setText(QApplication::translate("RQTGUIControlPluginWidget", "STOP", Q_NULLPTR));
        pause_2->setText(QApplication::translate("RQTGUIControlPluginWidget", "PAUSE", Q_NULLPTR));
        restart->setText(QApplication::translate("RQTGUIControlPluginWidget", "RESTART", Q_NULLPTR));
        start_3d_detection->setText(QApplication::translate("RQTGUIControlPluginWidget", "START 3D DETECTION", Q_NULLPTR));
        label_27->setText(QApplication::translate("RQTGUIControlPluginWidget", "                                          Auto Robot Operations", Q_NULLPTR));
        MANUAL->setTabText(MANUAL->indexOf(auto_2), QApplication::translate("RQTGUIControlPluginWidget", "AUTO", Q_NULLPTR));
        label_25->setText(QApplication::translate("RQTGUIControlPluginWidget", "                                     Robot Stats", Q_NULLPTR));
        label_88->setText(QApplication::translate("RQTGUIControlPluginWidget", "J5:", Q_NULLPTR));
        label_89->setText(QApplication::translate("RQTGUIControlPluginWidget", "J6:", Q_NULLPTR));
        label_90->setText(QApplication::translate("RQTGUIControlPluginWidget", "J4:", Q_NULLPTR));
        label_91->setText(QApplication::translate("RQTGUIControlPluginWidget", "J1:", Q_NULLPTR));
        label_92->setText(QApplication::translate("RQTGUIControlPluginWidget", "J2:", Q_NULLPTR));
        label_93->setText(QApplication::translate("RQTGUIControlPluginWidget", "J3:", Q_NULLPTR));
        label_29->setText(QApplication::translate("RQTGUIControlPluginWidget", "X:", Q_NULLPTR));
        label_36->setText(QApplication::translate("RQTGUIControlPluginWidget", "Y:", Q_NULLPTR));
        label_83->setText(QApplication::translate("RQTGUIControlPluginWidget", "Z:", Q_NULLPTR));
        label_84->setText(QApplication::translate("RQTGUIControlPluginWidget", "RY:", Q_NULLPTR));
        label_85->setText(QApplication::translate("RQTGUIControlPluginWidget", "RZ:", Q_NULLPTR));
        label_86->setText(QApplication::translate("RQTGUIControlPluginWidget", "RX:", Q_NULLPTR));
        IO->setTabText(IO->indexOf(tab), QApplication::translate("RQTGUIControlPluginWidget", "ROBOT STATUS", Q_NULLPTR));
        label_4->setText(QApplication::translate("RQTGUIControlPluginWidget", "DO 1:", Q_NULLPTR));
        label_5->setText(QApplication::translate("RQTGUIControlPluginWidget", "DO 2:", Q_NULLPTR));
        label_6->setText(QApplication::translate("RQTGUIControlPluginWidget", "DO 3:", Q_NULLPTR));
        label_7->setText(QApplication::translate("RQTGUIControlPluginWidget", "DO 4:", Q_NULLPTR));
        label_8->setText(QApplication::translate("RQTGUIControlPluginWidget", "DO 5:", Q_NULLPTR));
        label_9->setText(QApplication::translate("RQTGUIControlPluginWidget", "DO 6:", Q_NULLPTR));
        label_10->setText(QApplication::translate("RQTGUIControlPluginWidget", "DO 7:", Q_NULLPTR));
        label_11->setText(QApplication::translate("RQTGUIControlPluginWidget", "DO 8:", Q_NULLPTR));
        label_12->setText(QApplication::translate("RQTGUIControlPluginWidget", "DO 13:", Q_NULLPTR));
        label_13->setText(QApplication::translate("RQTGUIControlPluginWidget", "DO 11:", Q_NULLPTR));
        label_14->setText(QApplication::translate("RQTGUIControlPluginWidget", "DO 9:", Q_NULLPTR));
        label_15->setText(QApplication::translate("RQTGUIControlPluginWidget", "DO 12:", Q_NULLPTR));
        label_16->setText(QApplication::translate("RQTGUIControlPluginWidget", "DO 10:", Q_NULLPTR));
        label_17->setText(QApplication::translate("RQTGUIControlPluginWidget", "DO 14:", Q_NULLPTR));
        label_18->setText(QApplication::translate("RQTGUIControlPluginWidget", "DO 15:", Q_NULLPTR));
        label_19->setText(QApplication::translate("RQTGUIControlPluginWidget", "DO 20:", Q_NULLPTR));
        label_21->setText(QApplication::translate("RQTGUIControlPluginWidget", "DO 18:", Q_NULLPTR));
        label_22->setText(QApplication::translate("RQTGUIControlPluginWidget", "DO 16:", Q_NULLPTR));
        label_23->setText(QApplication::translate("RQTGUIControlPluginWidget", "DO 19:", Q_NULLPTR));
        label_24->setText(QApplication::translate("RQTGUIControlPluginWidget", "DO 17:", Q_NULLPTR));
        label_28->setText(QApplication::translate("RQTGUIControlPluginWidget", "DO 21:", Q_NULLPTR));
        label_30->setText(QApplication::translate("RQTGUIControlPluginWidget", "RDO 1:", Q_NULLPTR));
        label_31->setText(QApplication::translate("RQTGUIControlPluginWidget", "RDO 6:", Q_NULLPTR));
        label_32->setText(QApplication::translate("RQTGUIControlPluginWidget", "RDO 4:", Q_NULLPTR));
        label_33->setText(QApplication::translate("RQTGUIControlPluginWidget", "RDO 2:", Q_NULLPTR));
        label_34->setText(QApplication::translate("RQTGUIControlPluginWidget", "RDO 5:", Q_NULLPTR));
        label_35->setText(QApplication::translate("RQTGUIControlPluginWidget", "RDO 3:", Q_NULLPTR));
        label_37->setText(QApplication::translate("RQTGUIControlPluginWidget", "RDO 7:", Q_NULLPTR));
        comboBox->clear();
        comboBox->insertItems(0, QStringList()
         << QApplication::translate("RQTGUIControlPluginWidget", "DO 1:", Q_NULLPTR)
         << QApplication::translate("RQTGUIControlPluginWidget", "DO 2:", Q_NULLPTR)
         << QApplication::translate("RQTGUIControlPluginWidget", "DO 3:", Q_NULLPTR)
         << QApplication::translate("RQTGUIControlPluginWidget", "DO 4:", Q_NULLPTR)
         << QApplication::translate("RQTGUIControlPluginWidget", "DO 5:", Q_NULLPTR)
         << QApplication::translate("RQTGUIControlPluginWidget", "DO 6:", Q_NULLPTR)
         << QApplication::translate("RQTGUIControlPluginWidget", "DO 7:", Q_NULLPTR)
         << QApplication::translate("RQTGUIControlPluginWidget", "DO 8:", Q_NULLPTR)
         << QApplication::translate("RQTGUIControlPluginWidget", "DO 9 :", Q_NULLPTR)
         << QApplication::translate("RQTGUIControlPluginWidget", "DO 10:", Q_NULLPTR)
         << QApplication::translate("RQTGUIControlPluginWidget", "DO 11:", Q_NULLPTR)
         << QApplication::translate("RQTGUIControlPluginWidget", "DO 12:", Q_NULLPTR)
         << QApplication::translate("RQTGUIControlPluginWidget", "DO 13:", Q_NULLPTR)
         << QApplication::translate("RQTGUIControlPluginWidget", "DO 14:", Q_NULLPTR)
         << QApplication::translate("RQTGUIControlPluginWidget", "DO 15:", Q_NULLPTR)
         << QApplication::translate("RQTGUIControlPluginWidget", "DO 16:", Q_NULLPTR)
         << QApplication::translate("RQTGUIControlPluginWidget", "DO 17:", Q_NULLPTR)
         << QApplication::translate("RQTGUIControlPluginWidget", "DO 18:", Q_NULLPTR)
         << QApplication::translate("RQTGUIControlPluginWidget", "DO 19:", Q_NULLPTR)
         << QApplication::translate("RQTGUIControlPluginWidget", "DO 20:", Q_NULLPTR)
         << QApplication::translate("RQTGUIControlPluginWidget", "DO 21:", Q_NULLPTR)
         << QApplication::translate("RQTGUIControlPluginWidget", "RDO 1:", Q_NULLPTR)
         << QApplication::translate("RQTGUIControlPluginWidget", "RDO 2:", Q_NULLPTR)
         << QApplication::translate("RQTGUIControlPluginWidget", "RDO 3:", Q_NULLPTR)
         << QApplication::translate("RQTGUIControlPluginWidget", "RDO 4:", Q_NULLPTR)
         << QApplication::translate("RQTGUIControlPluginWidget", "RDO 5:", Q_NULLPTR)
         << QApplication::translate("RQTGUIControlPluginWidget", "RDO 6:", Q_NULLPTR)
         << QApplication::translate("RQTGUIControlPluginWidget", "RDO 7:", Q_NULLPTR)
        );
        io_on->setText(QApplication::translate("RQTGUIControlPluginWidget", " ON", Q_NULLPTR));
        io_off->setText(QApplication::translate("RQTGUIControlPluginWidget", " OFF", Q_NULLPTR));
        reset_all_io->setText(QApplication::translate("RQTGUIControlPluginWidget", "RESET ALL", Q_NULLPTR));
        IO->setTabText(IO->indexOf(tab_2), QApplication::translate("RQTGUIControlPluginWidget", "IO STATUS", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class RQTGUIControlPluginWidget: public Ui_RQTGUIControlPluginWidget {};
} // namespace Ui

QT_END_NAMESPACE

#endif // REAL_UI_H
